id = "the-pure-tone"
name = "The Pure Tone"
version = "0.0.2"
schema_version = 1
authors = [ "hupeh <hupeh@qq.com>" ]
description = "Pure and elegant color themes for zed"
repository = "https://github.com/hupeh/the-pure-tone"
